### ISSUE TITLE
Plex contact status open

### ISSUE THREAD

**Issue by Patrick1610** [lzilioli/plex-bridge-homebridge-http-webhooks#2]
Hi, 

I've just added the webhooks setup to my homebridge and the webhook to plex. 
In the home app the plex webhook always says open. 

I'm a beginner with homebridge and don't know webhooks at all but I would like to dim my lights when I start playing plex on my Chromecast or LG WebOS2 TV but I can't get it to work.

Any ideas?

**Comment by lzilioli** [comment]
I am getting ready to archive this repo. I still use a forked version locally, but it is highly customized to the point of not being open sourceable.

The original relatively simple purpose this repo intended to serve is met, in a more extensible manor by https://www.npmjs.com/package/homebridge-plex-sensors. I recommend it.
