### ISSUE TITLE
Multiple Triggers from Trailers

### ISSUE THREAD

**Issue by grokdesigns** [lzilioli/plex-bridge-homebridge-http-webhooks#4]
I'm having an issue with a short pre-roll trailer I have that plays before videos. The triggers work as expected, my lights turn off when playing a movie, then turn back on when paused or stopped, but they also turn back on after the 8 second trailer and then almost immediately back off when the movie starts, which is kind of annoying. I assume this would happen if you accidentally paused for a second or something too. Is there a way to catch this in the media.pause and media.stop payload events? Say, wait a couple of seconds, and if there is another play or resume event, then cancel changing the status?

**Comment by grokdesigns** [comment]
I tried editing the following:
```
if(payload.Metadata.type == 'track' || payload.Metadata.type == 'clip'){
    debug(`ignoring request because payload.Metadata.type === 'track' or 'clip'`)
    return;
  }
```
to catch when it was playing a clip. It seems to partially work, in that it doesn't trigger the lights off, but watching the logs, it seems to get stuck on 'Got webhook for media.scrobble' for quite some time. Eventually it does catch up, it turned the lights off about 2.5 minutes into the main movie.

**Comment by lzilioli** [comment]
I am getting ready to archive this repo. I still use a forked version locally, but it is highly customized to the point of not being open sourceable.

The original relatively simple purpose this repo intended to serve is met, in a more extensible manor by https://www.npmjs.com/package/homebridge-plex-sensors. I recommend it.
